"""followers

Revision ID: 935a50de82d0
Revises: 248f2a30adc8
Create Date: 2021-07-12 15:26:00.034719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935a50de82d0'
down_revision = '248f2a30adc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
